# Generated by Django 2.1.2 on 2018-11-02 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181101_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='plop', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='auteur',
            field=models.CharField(max_length=42, verbose_name='auteur'),
        ),
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Categorie', verbose_name='categorie'),
        ),
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=models.TextField(null=True, verbose_name='contenu'),
        ),
        migrations.AlterField(
            model_name='article',
            name='titre',
            field=models.CharField(max_length=100, verbose_name='titre'),
        ),
    ]
